### PR TITLE
Add some support for rails 5

### PR DESCRIPTION
**Pull request by hanselmw**
this fix Issue #69, letting cast all the values that used type_cast_from_user on active record 4.2

### CODE REVIEW

**Comment by JNajera** [comment]
Any news if this PR will be merged? Thanks!

**Comment by crismali** [comment]
@JNajera just merged. I'm going to make sure the tests check out and then cut a release.

**Comment by crismali** [comment]
v1.1.0 works on ActiveRecord 5.0 and 5.1

**Comment by JNajera** [comment]
Awesome! Thanks for the time.

**Pull request merged**
